#+author: George Kettleborough
#+hugo_base_dir: ../
#+hugo_categories: programming

* DONE Working on Multiple Web Projects with Docker Compose and Traefik :networking:web:development:traefik:docker:
CLOSED: [2023-10-02 Mon 09:00]
:PROPERTIES:
:EXPORT_FILE_NAME: multiple-web-projects-traefik
:EXPORT_HUGO_LASTMOD: [2023-10-19 Thu 21:24]
:END:

** Introduction                                                      :ignore:

Docker Compose is a brilliant tool for bringing up local development environments for
web projects.  But working with multiple projects can be a pain due to clashes.  For
example, all projects want to listen to port 80 (or perhaps one of the super common
higher ones like 8000 etc.).  This forces developers to only bring one project up at a
time, or hack the compose files to change the port numbers.

Recently I've found a way that makes managing these more enjoyable.

/2023-10-05 note: If this interesting to you, be sure to check out the comments about this
article on [[https://news.ycombinator.com/item?id=37756632][Hacker News]] for many other ideas./

/2023-10-19 note: I have now created a repo formalising the ideas in this post and some
of the Hacker News comments, here: https://github.com/georgek/traefik-local/

** A single project with Docker Compose

I use [[https://docs.docker.com/compose/][docker compose]] to manage local development instances of these projects.  A typical
compose file for a web project might look like this:

#+begin_src yaml
# proj/compose.yaml
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_DB: "proj"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"

  web:
    build: .
    depends_on:
      - "db"
    environment:
      DATABASE_URL: "postgres://user:pass@db/proj"
    ports:
      - "8000:80"
#+end_src

Note the very last line.  This is where we map port 8000 from the host to port 80 of the
container such that the service can be accessed via ~http://127.0.0.1:8000~.

This works quite well for a single project, but it suffers from a couple of problems if
you work on multiple projects:

1. It doesn't scale.  If I want to run another project at the same time, I'll have to
   use a different port number, maybe 8001, then 8002 etc.,

2. What if that ~compose.yaml~ file is checked in as part of the project? Does the whole
   team have to agree on a set of port numbers to use for each project?

** Using overrides for multiple projects

Fortunately Docker Compose does have a solution for (2) in the form of the
~compose.override.yaml~ file.  This file will be automatically be [[https://docs.docker.com/compose/multiple-compose-files/merge/][merged]] into the
~compose.yaml~ without any extra configuration.

Unlike some other guides (including the official [[https://docs.docker.com/compose/multiple-compose-files/merge/#example][docs]]) concerning this file, I prefer to
*not* check ~compose.override.yaml~ into version control and instead add it to the
~.gitignore~ file. Adding it to version control completely defeats the purpose of it: to
allow individual developers to override the standard compose file.

So, with this in mind, I no longer expose any ports by default in ~compose.yaml~ because
I don't know what will be convenient for each developer.  This set up might look like
this:

#+begin_src yaml
# compose.yaml
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_DB: "proj"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"

  web:
    build: .
    depends_on:
      - "db"
    environment:
      DATABASE_URL: "postgres://user:pass@db/proj"
#+end_src

#+begin_src yaml
# compose.override.yaml (to be created by each developer)
services:
  web:
    ports:
      - "8000:80"
#+end_src

** Using Traefik

So now each developer can pick their own port numbers for each project, but we can still
do better than this.  People aren't good at remembering numbers.  We are much better at
remembering names.  [[https://doc.traefik.io/traefik/][Traefik]] is a free software edge router that can be used as a simple
and super easy to configure reverse-proxy in container-based set ups.

Using Docker, Traefik can automatically discover services to create routes to.  It uses
container labels to further configure these routes.  The following tiny example from the
[[https://doc.traefik.io/traefik/getting-started/quick-start/][docs]] is illustrative:

#+begin_src yaml
# traefik/compose.yaml
services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
#+end_src

This starts two containers on the same docker network.  The reverse proxy listens on
port 80 and forwards traffic with a host header of "whoami.docker.localhost" to the
~whoami~ service.  Traefik guesses which port to send it to ~whoami~ based on the ports
exposed by the container.

If you haven't played with Traefik before it's worth going through the [[https://doc.traefik.io/traefik/getting-started/quick-start/][quick-start]]
properly now then coming back to see how we can make this work for multiple projects.

** Traefik with multiple projects

This doesn't quite solve our problem yet.  We don't want all of our various projects
inside one compose file.  Luckily Traefik communicates with the Docker daemon directly
and doesn't really care about the compose file, but you do need to make sure a few
things are in order for this to work.

Firstly, make a docker network especially for Traefik to communicate with other services
that you want to expose, for example:

#+begin_src yaml
# traefik/compose.yaml
services:
  reverse-proxy:
    image: traefik:v2.10
    restart: unless-stopped
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik

networks:
  traefik:
    attachable: true
    name: traefik
#+end_src

We create the network ~traefik~ and give it the name "traefik" (otherwise docker compose
would scope it by project, e.g. "traefik_traefik").  We also allow other containers to
attach to this network.

Then in our ~compose.override.yaml~ file from above, instead of mapping ports, we do the
following:

#+begin_src yaml
# proj/compose.override.yaml
services:
  web:
    labels:
      - "traefik.http.routers.proj.rule=Host(`proj.traefik.me`)"
      - "traefik.http.services.proj.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik"
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
#+end_src

Now, after bringing up first the traefik project then your web project, you should be
able to browse to [[http://proj.traefik.me/]] in your web browser.

There's a few things going on here.  First, we have declared the ~traefik~ network as an
external network.  This means compose won't manage it, but expects it to exist (so you
must start your traefik composition first).  Next we override the ~networks~ setting of
~web~ to make it part of the ~traefik~ network too.  Note we also have to add the
~default~ network, otherwise it wouldn't be able to communicate with ~db~ and other
services on its own default network.

The ~traefik.http.routers.proj.rule~ label configures Traefik to route HTTP traffic with
the "proj.traefik.me" hostname to the container. The ~traffic.docker.network~ label is
necessary because ~web~ is on two networks.  Finally, we set
~traefik.http.services.proj.loadbalancer.server.port~ for completeness, just in case
your container needs a different port mapping than the port it is set to expose, or if
it exposes multiple ports.

There is one final piece of magic: the "traefik.me" hostname.  What is that?  You can
read about it at [[http://traefik.me/]].  Essentially it is a DNS service that resolves to
any IP address that you want, but by default it resolves ~<xxx>.traefik.me~ to
~127.0.0.1~.  There are other services like this including [[https://sslip.io/]] and
[[https://nip.io/]].

Now, because we don't need to define any ports at all, it is possible to take advantage
of a newish compose feature and reinstate the ports in the original ~compose.yaml~ file
for those developers who don't want to set up Traefik for themselves.  So our final
configuration looks like this:

#+begin_src yaml
# compose.yaml
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_DB: "proj"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"

  web:
    build: .
    depends_on:
      - "db"
    environment:
      DATABASE_URL: "postgres://user:pass@db/proj"
    ports:
      - "8000:80"
#+end_src

#+begin_src yaml
# compose.override.yaml (to be created by each developer)
services:
  web:
    labels:
      - "traefik.http.routers.proj.rule=Host(`proj.traefik.me`)"
      - "traefik.http.services.proj.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik"
    networks:
      - default
      - traefik
    ports: !reset []

networks:
  traefik:
    external: true
#+end_src

The ~!reset []~ tag sets the ports back to empty; you can read about it [[https://docs.docker.com/compose/compose-file/13-merge/#reset-value][here]].  Note that
unfortunately it can't be used to set /new/ ports, only reset them to default (you would
have to use two layers of override file to set new ports).  The ~!reset~ tag requires a
fairly recent version of docker compose, at least greater than 2.18.0.

A final note: you can check that these overrides are working correctly by running
~docker compose config~.

** Conclusion

By leveraging both the ~compose.override.yaml~ file and Traefik it's easy to run
multiple web projects on your development system at the same time and have easy to
remember names to access them all.  Each developer is free to run as many as they want
and create their own easily-manageable configurations.  Traefik and traefik.me can also
be used to allow other developers on your network to easily access your local
development instances with no DNS configuration required.

It's a shame that the docs instruct people to use the override file for a distributed
developer config rather than let individual developers use it, but hopefully it's not
too hard to remove this file from repos if already present.

* DONE My 2023 Emacs Python Setup                              :emacs:python:
CLOSED: [2023-08-15 Tue 14:19]
:PROPERTIES:
:EXPORT_FILE_NAME: emacs-python-2023
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :description My new configuration with Emacs 29, Eglot, python-lsp-server and tree-sitter
:END:

** Introduction                                                      :ignore:

I've been using Emacs for almost 15 years now.  Somewhat surprisingly, I hadn't touched
my config in three years!  It's been working that well.  But now that Emacs 29 has been
released I've decided to take a look at what's new and there have been some big changes,
particularly for Python.

** Goodbye Elpy, Goodbye Projectile

[[https://github.com/jorgenschaefer/elpy/][Elpy]] has been the primary mode for Python development for me for years now.  But sadly,
it looks like the project is no more.  The good news is there are better ways to do what
it did.  It's bittersweet to say goodbye to it and I will be eternally grateful to the
authors, but progress is progress.

Similarly, [[https://github.com/bbatsov/projectile][Projectile]] was what I used to manage projects.  But now Emacs has project.el
built in and I've opted to use that instead.  One nice thing about project.el is it uses
other standard stuff underneath like xref.  I configured xref to use [[https://github.com/BurntSushi/ripgrep][Ripgrep]] and now the
Project commands like ~C-x p g~ use Ripgrep:

#+begin_src elisp
(use-package xref
  :config
  (setq xref-search-program 'ripgrep))
#+end_src

** Native builds and tree-sitter

I always build Emacs myself from source if I can.  I run Gentoo on my personal computer
so that goes without saying, but I do it on Ubuntu too, if only to get the latest
versions.  This does mean I can easily enable a couple of new features: native builds
and tree-sitter.

On Gentoo this was a simple as adding a couple of USE flags to portage.  My USE flags
for emacs now look like:

#+begin_src
app-editors/emacs athena cairo gui gtk harfbuzz json libxml2 source tree-sitter jit -X
#+end_src

The ~gtk -X~ also implies a ~pgtk~ build which is nice because I use wayland (sway).

On Ubuntu (20.04, yeah, old, this is one reason I prefer rolling distros) it was more
difficult.  I first pulled the source code (~emacs-29.1.tar.gz~) from a [[http://ftpmirror.gnu.org/emacs/][nearby GNU
mirror]] per the [[https://www.gnu.org/software/emacs/download.html][GNU website]].  Then a few packages are required (I use i3/X11 on
Ubuntu):

#+begin_src bash
sudo apt install autoconf make gcc texinfo libgtk-3-dev libxpm-dev libjpeg-dev \
     libgif-dev libtiff5-dev libgnutls28-dev libncurses5-dev libjansson-dev \
     libharfbuzz-dev libharfbuzz-bin imagemagick libmagickwand-dev libgccjit-10-dev \
     libgccjit0 gcc-10 libjansson4 libjansson-dev xaw3dg-dev texinfo libx11-dev
#+end_src

Now, because ~libgccjit~ (required for native builds) is only for GCC 10, the build
process has to be configured for GCC 10 specifically, in addition to enabling all the
wanted features:

#+begin_src bash
CC="gcc-10" ./configure --prefix=$HOME --with-json --with-native-compilation=aot \
  --with-modules --with-compress-install --with-threads --with-included-regex \
  --with-x-toolkit=lucid --with-zlib --with-jpeg --with-png --with-imagemagick \
  --with-tiff --with-xpm --with-gnutls --with-xft --with-xml2 --with-mailutils \
  --with-tree-sitter
#+end_src

Note that I keep my own builds in ~$HOME~ by setting ~--prefix~.  By default the
installation would put it in the system directories which I prefer not to do as those
are controlled by my system package manager.  Also note that I set
~--with-native-compilation=aot~ which makes native builds ahead of time instead of JIT
compiling them.  Run ~./configure --help~ to see all of the build options.

Then I just compiled it:

#+begin_src bash
make -j 8                       # 8 threads
#+end_src

The build can be tested with ~src/emacs -Q~ then, if it works:

#+begin_src bash
make install
#+end_src

** Eglot

Elpy provided a proper IDE experience for Python but it did it in a completely custom,
albeit very clever, way via a special RPC process which used ~jedi~.  Now with LSP we
can get essentially the same sort of thing but in a more standard way that works with
all languages.

I have tried LSP (in particular, [[https://emacs-lsp.github.io/lsp-mode/][~lsp-mode~]]) in emacs before, but I wasn't impressed.  I
cannot stand latency and the moment I detect latency when merely typing in a text
editor, I walk away.  But I'm pleased to say that with Emacs 29, native builds, Eglot
and [[https://github.com/python-lsp/python-lsp-server][~python-lsp-server~]] it is now fast enough for me.  ~lsp-mode~ might very well be
fast enough now too.  I'll probably try it eventually.

I installed ~python-lsp-server~ (with [[https://github.com/pypa/pipx][~pipx~]] on Ubuntu).  This is my preferred way of
installing Python apps if they're not available in the base distro.  Notice how there
will be only one LSP server installed for my whole system (not one per virtualenv).

Enabling Eglot is easy.  To make it work for Python it just needs the following:

#+begin_src elisp
(use-package eglot
  :hook (python-mode . eglot-ensure))
#+end_src

Now just open a Python file and it should work.  It does everything Elpy did (or, at
least, what I used it for) and more.  Just like that.

By default, Eglot uses Flymake.  I had previously been using Flycheck.  I can't really
remember why, to be honest, so I'll try using Flymake instead and say goodbye to
Flycheck for now too.

** Virtualenvs

OK, so, it doesn't completely just work.  One of the most important things for me is
being able to jump to the definition of a symbol in the source.  This does just work for
first party stuff and (kinda) for standard library stuff, but it won't work for third
party stuff.  That's because the LSP server doesn't know where to find those libraries.

Usually when developing on a Python project one would create a virtual environment for
it.  I make everything a package such that doing a ~pip install -e .~ installs the
package and all of its dependencies into the virtualenv.  Then you just need to make the
LSP server aware of this environment.

I used to use ~virtualenvwrapper~ to create virtualenvs for each project, but I've found
a better way: [[https://direnv.net/][~direnv~]].  This allows you to create ~.envrc~ files in directories with
anything you want in it then automatically loads it into your environment when you
change to that directory.  What's even neater is it has built-in support for Python (and
other languages).

To install ~direnv~ on Gentoo I used the [[https://github.com/gentoo-mirror/guru][Guru]] overlay:

#+begin_src bash
eselect repository enable guru
#+end_src

After installing and setting up ~direnv~, make a file called ~.envrc~ at the top of your
project and put the following:

#+begin_src bash
layout python
#+end_src

That's it!  After enabling your project for ~direnv~ support it will automatically
create a virtualenv and activate it.  When you change directory, it will deactivate it.
Amazing!

In Emacs you can install the ~direnv~ package and enable it:

#+begin_src elisp
(use-package direnv
  :config
  (direnv-mode))
#+end_src

Now when you browse to a project with a ~.envrc~ file it will just work.

** Tree-sitter

Finally, to enable tree-sitter I needed to first install the grammar for Python, I added
the following to my emacs config:

#+begin_src elisp
(setq treesit-language-source-alist
   '((python "https://github.com/tree-sitter/tree-sitter-python")))
#+end_src

And then (after evaling the above) you can run: ~M-x treesit-install-language-grammar~.
This builds the grammar for you and puts it in your emacs config.

Now you can use the mode ~python-ts-mode~ instead of ~python-mode~:

#+begin_src elisp
(use-package python
  :mode ("\\.py\\'" . python-ts-mode)
  :init
  (add-to-list 'major-mode-remap-alist '(python-mode . python-ts-mode)))
#+end_src

The ~major-mode-remap-list~ entry means ~python-ts-mode~ will be used whenever
~python-mode~ would have been used, like when opening a script with no file extension
but a Python shebang.

** Completion

One thing I cannot do without is some kind of completion capability.  In bash I use
tab-completion extensively and I consider any keyboard-driven software that doesn't
support at least tab-completion to be defective.

Basic completion is supported in Emacs out of the box but it can be extended to be quite
sophisticated.  But I've always found it a bit overwhelming.  My life was changed when I
first enabled [[https://www.gnu.org/software/emacs/manual/html_mono/ido.html][ido]].  The combination of completion and narrowing is amazing.  Later I
switched to other packages like [[https://github.com/abo-abo/swiper][ivy]], [[https://emacs-helm.github.io/helm/][Helm]] and [[https://github.com/radian-software/selectrum][Selectrum]] and enabled in-buffer completion
with [[https://company-mode.github.io/][Company]].  Selectrum is now defunct and replaced with [[https://github.com/minad/vertico][Vertico]].

For the first time, I have a completion set up that I understand and that I'm very happy
with.

What I really wanted was fuzzy-style completion in minibuffer contexts but dead basic
prefix-style completion within buffers.  I also want the completion within-buffer to be
driven by the tab key like in a bash shell.  I've settled on Company within-buffer and
Vertico in the minibuffer.

I like the setting ~(setq tab-always-indent 'complete)~ which causes TAB to indent
first, then complete, but I was getting weird behaviour where that completion would not
launch company.  So instead:

#+begin_src elisp
(global-set-key (kbd "TAB") #'company-indent-or-complete-common)
#+end_src

This now does the right thing but launches Company instead of the default completion
function.

The other major part is completion styles.  I like the [[https://github.com/oantolin/orderless][Orderless]] style for the fuzzy
minibuffer style, but it doesn't work for basic completion.  Emacs supports setting a
list of completion styles by setting ~completion-styles~ and further refining that for
specific categories by setting ~completion-category-overrides~.  The trouble is, the
category names for the latter are quite hard to find.  But eventually I settled on the
following configuration:

#+begin_src elisp
(use-package orderless
  :init
  (setq completion-styles '(basic partial-completion orderless)
        completion-category-defaults nil
        completion-category-overrides '((project-file (styles orderless))
                                        (buffer (styles orderless))
                                        (command (styles orderless)))))
#+end_src

This sets ~basic~ and ~partial-completion~ styles first by default everywhere.  Company
doesn't really support the Orderless style, which is fine by me as I don't want it
in-buffer anyway.  I then override it for particular categories to add ~orderless~ to
the front.  ~project-file~ is for finding files in projects with ~C-x p f~, ~buffer~ is
for switching buffers and ~command~ is for running commands with ~M-x~.

** Conclusion

To sum up, I've switched from Projectile to project.el, from Elpy to Eglot/LSP and from
virtualenvwrapper to direnv as well as including the latest improvements like native
builds and tree-sitter.  This has really simplified my config and I seem to have a
renewed love for Emacs.

I've been using this configuration for a few days now for real work and I really love it
so far.  Things like the eldoc and xref jump to definition features are working
perfectly now and I've had real trouble with consistent behaviour before.

My actual emacs config does include a number of extra tweaks to all of this stuff.  I
love reading other people's .emacs files, so maybe you'll enjoy reading mine too:
https://github.com/georgek/dot-emacs

Happy hacking!

* DONE Arduino Programming with Emacs :emacs:arduino:programming:electronics:
CLOSED: [2023-07-31 Mon 19:30]
:PROPERTIES:
:EXPORT_FILE_NAME: emacs-arduino
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :summary Develop for Arduino in your favourite text editor with PlatformIO
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :description An easy way to start Arduino for Emacs users
:END:

** Introduction                                                      :ignore:

If you want to start Arduino programming you'll notice a lot of the documentation and
tutorials are centred around the Arduino IDE.  Now, obviously, as an Emacs user you'll
be loath to install something like Arduino IDE, let alone actually use it.  The good
news is it's super easy to get started with Arduino with any editor, including Emacs and
even Vim if you so desire.

All the Arduino IDE is doing is calling a cross-compiler toolchain then using [[https://github.com/avrdudes/avrdude][~avrdude~]]
to communicate with the Arduino to upload software.  The Arduino Uno and Nano both use
the Atmel AVR platform so what you need is a toolchain that can target that platform.
Now, you could install your own toolchain and call ~avrdude~ directly.  If you know how
to do that then I guess you can stop reading now.  But if you don't, or aren't
interested in learning how (it's not very interesting), then read on.

** PlatformIO

[[https://platformio.org/][PlatformIO]] is a project that makes it really easy to do embedded development.

First, install PlatformIO, I like to use [[https://github.com/pypa/pipx][pipx]] to install tools like this: ~pipx install
platformio~.

Now, start your project by making a directory for it:

#+BEGIN_SRC sh
mkdir my_new_project
cd my_new_project
#+END_SRC

And initialise a PlatformIO project:

#+BEGIN_SRC sh
platformio project init --board uno --board nanoatmega328
#+END_SRC

This will configure your project for both Arduino Uno and Nano.

Now write some barebones C++ code that does nothing in ~src/main.cpp~:

#+BEGIN_SRC cpp
#include "Arduino.h"

void setup()
{
    // your setup code here
}

void loop()
{
    // your main loop here
}
#+END_SRC

This is, of course, totally standard C++ so you can use your normal C++ modes etc.

You should end up with a project structure like this:

#+BEGIN_SRC text
.
├── include
│   └── README
├── lib
│   └── README
├── platformio.ini
├── src
│   └── main.cpp
└── test
    └── README
#+END_SRC

Now you can simply run the following to build the software for all platforms specified
in ~platformio.ini~:

#+BEGIN_SRC sh
platformio run
#+END_SRC

To build /and/ upload the software to your Arduino, if you are on Linux you first have
to install some udev rules:
https://docs.platformio.org/en/latest/core/installation/udev-rules.html

Then you can run simply:

#+BEGIN_SRC sh
platformio run -e nanoatmega328 -t upload # for arduino nano
platformio run -e uni -t upload # for arduino uno
#+END_SRC

This tends to cleverly pick the right serial device but if you have more than one you
might need to specify it with [[https://docs.platformio.org/en/latest/core/userguide/cmd_run.html#cmdoption-pio-run-upload-port][~--upload-port~]].

You can adapt these as your command for ~M-x compile~ or write a ~Makefile~ if you
prefer.  Don't forget it expects to be run from the top-level where ~platformio.ini~
lives, though.

Another super-useful command to be aware of is ~platformio device monitor~.  This gives
you a serial terminal for communicating with your device.  Really convenient.  There's a
lot more too.

And that's it!  You'll find the Arduino documentation here:
https://www.arduino.cc/reference/en/ That's all you should need to get started.  Happy
hacking!
