#+author: George Kettleborough
#+hugo_draft: t
#+hugo_base_dir: ../
#+hugo_categories: Technology

* DONE Just Send Me the Prompt                                       :llm:ai:
CLOSED: [2025-07-31 Thu 09:41]
:PROPERTIES:
:EXPORT_FILE_NAME: just-send-me-the-prompt
:END:

If you are thinking about using an LLM to communicate with me, you will be glad to hear
I've just developed an exciting new technique which will save us both time. Rarely are
such wins possible, so this is surely cause for a celebration.

The technique goes as follows:

1. Type up your LLM prompt,
2. (Here's where it gets really exciting), instead of sending your prompt to an LLM,
   just send the prompt directly to me!

"What?" I hear you asking, "My prompt doesn't contain all the information you need!"

But it does. You can't create information from thin air and I too have access to LLMs.
If I want to bloat your information a hundred fold by incorporating generic drivel I can
do it myself. I could even do it using the LLM of my choice and tweak the prompt to make
it more or less verbose.

However, we are barely scratching the surface of what's possible here. Because, you see,
/I won't even feed your prompt to an LLM at all!/

OK, I know this sounds insane but hear me out: I have the very same language processing
capabilities built into my brain. An organic language model, you might say. It's even
quite large, if I may be forgiven for boasting. I can understand a fair bit but,
admittedly, I can't understand everything. Luckily I /also/ have circuits I've developed
that tell me whether I really understand something or not.

So what if I don't understand? What if your prompt is too terse? Too devoid of context?
I could always fall back to feeding it to the LLM after all, but ultimately the LLM
won't have any more information than what's the in prompt, it will just be guessing the
details. So what then?

This all depends on the medium of communication.

If it's an email you've sent me, I will simply reply to you (sending you my prompt
directly, of course) asking for clarification or more details. You can then amend your
prompt as you would normally and send it back.

If it's a published work such as a book or marketing literature then I'm more limited in
my recourse and I will likely just leave a bad review or not buy your product etc.

Either way, together we will learn to communicate clearly and effectively
together. We'll learn to be clear and concise in our prompts and be fully aware of
implicit context at all times. I believe it's called prompt engineering, but I prefer
the older terminology: writing.

* TODO My Eight Year Old PC
:PROPERTIES:
:EXPORT_FILE_NAME: my-eight-year-old-pc
:END:

I like computers. I own and run a few types but my favourite by far is my desktop
[[https://en.wikipedia.org/wiki/IBM_PC_compatible][PC]]. What's great about these computers is they can fit almost any budget but through
upgrades can be made to last a very long time. This is great for reducing waste and
provides pleasure for the PC owner.

This post is about my current PC which is now over eight years old. In that time it has
outlived two corporate work laptops (the latest one had soldered-in RAM so had to be
replaced when more memory was needed) and, thanks to my choice of a lean [[https://www.gentoo.org/][Gentoo]]
GNU/Linux system, performs at least as well as any other computer I use.

The computer is, of course, a [[https://en.wikipedia.org/wiki/Ship_of_Theseus][Trigger's broom]] at this point; the only original
components remaining are the motherboard, PSU and some memory (the case is still in use
in another build). The careful PC builder will always slightly over budget for
motherboard, PSU and case and under-budget the rest, as they are all easily replaceable
later.

** Original configuration

In the summer of 2015 my PC was built with the following configuration:

| Part        | Model                             |
|-------------+-----------------------------------|
| Motherboard | Asus Z97M-Plus                    |
| CPU         | Intel Pentium K G3258             |
| RAM         | 16 GiB Corsair DDR3 1600 MHz        |
| SSD         | 250 GiB Samsung 850 EVO            |
| PSU         | SuperFlower Leadex Platinum 550 W  |
| Case        | Fractal Design Node 804           |
| Cooler      | Be Quiet! Shadow Rock Low Profile |

The really amazing part of this build was the CPU. On the face of it it's an
underpowered budget chip, but it had remarkable overclocking potential. In fact, I
overclocked it from it's stock 3.2 GHz to 4.2 GHz with barely any increase in
temperature. This was known to work well with the stock cooler, which was included in
the tiny £50 price tag. Some overclockers were able to get up to 4.8 GHz from this CPU,
but I wanted to ensure it lasted.

This computer has only ever booted Linux. I started off with Ubuntu but settled on
Gentoo around 6 years ago. I run a minimal system and spend most of my time in Emacs and
Firefox.

The case also housed 3 hard disks that I had from previous builds.

** Case swap

In 2020 I decided to build a [[https://en.wikipedia.org/wiki/Network-attached_storage][NAS]] and move the majority of my storage there. The Node 804
case seemed perfect for the NAS, so I moved the components of my PC to a new Fractal
Design Define Mini C freeing up the original Node 804 for the NAS. Due to everything
being Micro ATX this was a simple unscrew and transplant taking no more than an hour.

** Upgrade to best CPU

The best CPU for the socket is the 4790K. This sold for around £300 when it was new, but
they held their value very well. I was able to get one for around £140 in 2023. Crazy
that they still go for so much, but it's still better than replacing my entire
system. Naturally I have overclocked this to 4.6 GHz but unlike the G3258 it needs a
bigger cooler. At the same time I thought I might as well upgrade my memory to 32 GiB
since it's not unknown for GCC to use 4 GiB per thread when compiling. This was quite a
big upgrade and made my system noticeably faster.

** 4K screens

One thing I'd been thinking about for a while is having high-DPI screens. This
essentially means 4K screens and running them scaled 2x.

* TODO Fixing my JVC DLA-X5000 Projector
:PROPERTIES:
:EXPORT_FILE_NAME: fixing-dla-x5000
:END:
