#+author: George Kettleborough
#+hugo_draft: t
#+hugo_base_dir: ../
#+hugo_categories: Travel
#+hugo_paired_shortcodes: pictures
#+html_container: section
#+html_container_nested: t

* TODO Norfolk Coast Path                     :walking:britain:nationaltrail:
:PROPERTIES:
:EXPORT_FILE_NAME: norfolk-coast-path
:END:

The Norfolk Coast Path (NCP) is a waymarked, long-distance footpath and [[https://www.nationaltrail.co.uk/][National Trail]]
in England. It stretches from Hunstanton all the way along the Norfolk coastline to
Hopton. I walked it with my partner [[https://www.peregrinavicki.com/][Vicki]] over the course of seven days in
September 2022.

#+begin_pictures
ncp/DSC_1821|A view from a hill next to the sea with sea and houses visible.|The view from the Beaston bump.
ncp/DSC_1822
ncp/DSC_1826
ncp/DSC_1828
ncp/DSC_1831
ncp/DSC_1844
ncp/DSC_1847
#+end_pictures

** Planning

The NCP is around 135 km (83 miles) long and quite flat. The way is mostly on good, well
trodden paths with some slower sections on sandy and shingle beaches (but you can often
choose to walk inland on firmer ground instead). Fortunately there are no pebbles and
the shingles didn't become too tiring.

#+hugo: {{<map main-map=true tiles-url="/ncp/ncp.osm.pmtiles" tracks="/ncp/trk/day1.gpx,/ncp/trk/day2.gpx,/ncp/trk/day3.gpx,/ncp/trk/day4.gpx,/ncp/trk/day5.gpx,/ncp/trk/day6.gpx,/ncp/trk/day7.gpx" points="0.4887009970843792:52.94428450986743,0.6836324650794268:52.96570463106036,0.8525082003325224:52.95722373761237,1.0182195156812668:52.95657833106816,1.2131382431834936:52.94532135128975,1.4773163013160229:52.85447761416435,1.7025797814130783:52.68969677388668,1.7221770901232958:52.53826973028481" bounds="0.396881,52.495323,1.812744,53.023870" max-bounds="0.396881,52.495323,1.893768,53.078353">}}

There is only one section---the very last section between Gorleston and Hopton---that
*cannot be walked at high tide*. Other sections are not affected as the waymarkers will
take you away from any tidal sections. However, people can and do get caught out by the
incoming tide on the vast sandy beaches around Holkham and Wells (look out for the
amusing warning signs). It's not really a problem when you're on the move, but don't
walk out too far if you're not sure.

At 135 km the NCP can be walked comfortably in 7 days for most of the year. We walked it
over the course of two regular weekends and one three day long weekend. In terms of
provisions the NCP is split into two distinct halves.  Originally the NCP only ran from
Hunstanton to Cromer. This is the first four days' walking and is well provisioned in
terms of shops, transport and accommodation.  In 2016 it was extended from Cromer to
Hopton. This part is considerably more remote with very few options for accommodation
and transport.

Starting from Hunstanton, the seven days end fairly evenly at towns and villages along
the way:
- Hunstanton
- Burnham Deepdale (20 km)
- Wells (17 km)
- Blakeney (12 km)
- Sheringham (16 km)
- Bacton (23 km)
- Hemsby (25 km)
- Hopton (20 km)

We weren't able to find accommodation in all of these places and had to use public
transport to help.

For the first weekend we stayed overnight in a private room at [[https://deepdalecamping.co.uk/][Deepdale Backpackers]] in
Burnham Deepdale then took the [[https://www.lynxbus.co.uk/bus-routes/coastliner-36/][Coastliner]] bus back from Wells to Hunstanton.

On the second weekend we parked at Blakeney and caught the bus to Wells then walked back
to Blakeney. We were unable to find accommodation in Blakeney so drove to the [[https://www.yha.org.uk/hostel/yha-sheringham][YHA]] in
Sheringham. We then took the bus back to Blakeney and walked back to Sheringham.

The last three days really need to be done in one go as there are no buses at all on
this section. We parked in Norwich and took the train to Sheringham to start. There are
a few places to stay around Bacton but they are either ridiculously expensive or not
available when you want them. We ended up staying in the pub in North Walsham and had to
resort to a taxi to take us from/to the NCP at Bacton. Even the taxi was quite hard to
come by on the bank holiday weekend. On the second night we were able to stay in a
holiday home in Hemsby. This was by far the hardest bit to plan.

** Walking

#+hugo: {{<mini-map-section>}}

*** Day 1: Hunstanton to Burnham Deepdale
# 4th September 2022

#+hugo: {{<mini-map-bounds bounds="0.4887009970843792,52.970074117183685,0.6839822418987751,52.94412994757295">}}

#+begin_pictures
ncp/day1/IMG_1401
ncp/day1/IMG_1429
ncp/day1/IMG_1430
ncp/day1/IMG_1492
ncp/day1/IMG_1528
ncp/day1/IMG_1550
ncp/day1/IMG_1553
#+end_pictures

The walk starts in the lovely seaside town of Hunstanton. The waymarkers take you on top
of the cliff away from the amusements and towards Old Hunstanton. We walked this way
because the tide was in but at low tide you can (and should) walk down to the beach and
walk that way to see the interesting and unique two-tone cliffs and, at very low tide, a
small shipwreck.

At this time in the morning there weren't many people on the beach at Old
Hunstanton. The NCP took us away from the beach, behind the chalets and eventually into
the dunes next to a golf course. We found ourselves walking through waist high foliage
and dodging brambles. Classic British walking, but probably the only instance of this on
the whole trail.

Before long the NCP meets the end of Peddar's Way, another National Trail in Norfolk. It
was at this point our route was diverted due to the boardwalk at Holme being closed for
repairs (and natterjack toads). The diversion took us inland up a considerable hill (for
Norfolk) with lovely views. Although that was nice, the way back down was a bit of a
trudge.

When we returned to the real NCP the sandy beaches had given way to salt marshes. This
would be a familiar sight for the next few days. Much of the coastline here is
inaccessible due to mud and deep tidal inlets. The saltmarshes are a strange place. From
afar they look like land, but close up you realise they belong to the sea.

At Brancaster the walk follows a long boardwalk. This was in slight disrepair and there
were some signs suggesting we shouldn't walk that way. But the alternative was next to a
road, so we did and it was fine apart from the odd broken plank. After the boardwalk we
shortly arrived in Burnham Deepdale for the end of the day.

*** Day 2: Burnham Deepdale to Wells-next-the-Sea
# 5th September 2022

#+hugo: {{<mini-map-bounds bounds="0.6836324650794268,52.97974926419556,0.852420860901475,52.95720923691988">}}

#+begin_pictures
ncp/day2/IMG_1654
ncp/day2/IMG_1678
ncp/day2/IMG_1718
ncp/day2/IMG_1696
ncp/day2/IMG_1812
ncp/day2/DSC_1791
ncp/day2/IMG_1832
#+end_pictures

The second day started with us walking right out to the saltmarshes, far away from the
villages. It was necessary for the path to dart back inland to cross the river Burn just
before Burnham Overy Staithe.

We started to notice the car of choice around these parts is a beastly Range Rover,
Porsche or even Rolls Royce. It turns out a lot of money has moved here giving Burnham
Market its nickname: "Burnham Upmarket".

After the detour inland it was back out to sea and briefly back to sandy beaches. The
beach at Holkham and onwards to Wells is one of the most beautiful in Norfolk. At low
tide the sands seem endless. We walked partly out on the beach, looking for shells, and
partly inland a bit in the woods when the sand became too tiring.

The beach stops abruptly at Wells. You can swim over to the sand on the other side of an
inlet, but this is otherwise inaccessible due to the return of the salt marshes. From
the end of the beach it's a long walk back along the top of the sea wall to Wells.

Wells is another pretty seaside town and the end of our day. After a brief visit to the
souvenir shops we took the bus all the way back to Hunstanton. The bus ride back was
rather scenic and provided a nice reflection of the walk so far.

*** Day 3: Wells-next-the-Sea to Blakeney
# 10th September 2022

#+hugo: {{<mini-map-bounds bounds="0.8525082003325224,52.95927571132779,1.0148312151432037,52.94912748970091">}}

#+begin_pictures
ncp/day3/IMG_1897
ncp/day3/IMG_1941
ncp/day3/IMG_1962
ncp/day3/IMG_1993
ncp/day3/IMG_2014
ncp/day3/IMG_2019
ncp/day3/IMG_2036
#+end_pictures

We started this day at the end---Blakeney---and caught the bus back to the start at
Wells. While waiting for the bus we visited Buoy Coffee which is, sadly, no longer
there, but served delicious coffee from Grey Seal Coffee in Cromer.

This day was quite different to the others: while the smell of sea always filled our
noses, it was not visible. The walk was entirely by salt marshes and was even muddy in
places. At low tide you can supposedly walk across the marshes, but the slippery mud and
deep gullies are not very inviting. At one part there was even recent fire damage to the
vegetation.

Somewhere around Stiffkey we spotted several Spoonbills in the air. Some birdwatchers
kindly let us observe them nesting in the marshes. Apparently they've recently started
breeding in Norfolk after being absent from Britain for hundreds of years.

We took a detour into Stiffkey to have some coffee and lunch from Stiffkey Stores. This
was convenient because at only 12 km this was our shortest day by far. It seemed a shame
to do such a short day since some of the later days would be more than twice as long,
but it was the only way we could figure out. We ended the day by driving to Sheringham
where we would sleep.

*** Day 4: Blakeney to Sheringham
# 11th September 2022

#+hugo: {{<mini-map-bounds bounds="1.0178787913173437,52.96580362133682,1.2116400618106127,52.94537323527038">}}

#+begin_pictures
ncp/day4/IMG_2154
ncp/day4/IMG_2156
ncp/day4/IMG_2165
ncp/day4/IMG_2181
ncp/day4/IMG_2258
ncp/day4/IMG_2262
ncp/day4/IMG_2277
#+end_pictures

Like the previous day we started at the end and caught a bus back to the start. It would
be our last visit to Blakeney so we were happy to visit Buoy Coffee again. After a
not-so-brief stop to count all the different types of ducks in the pond near the car
park it was back into the now familiar salt marshes.

It wouldn't be too long before we were heading back inland towards Cley (pronounced
ˈklaɪ, to rhyme with "eye") and its famous windmill. This is necessary to cross the
River Glaven. We walked along narrow flood defence structures and across the bridge
towards the windmill.

After Cley it was finally back out to the sea again and a classic Norfolk scene: big
blue skies, green dunes and a golden, lightly shingled beach.  It was a long walk along
the beach with Sheringham ever in sight. Shingles are tiring to walk on, but there are
enough compacted sand sections to ease the passage. We couldn't resist playing in the
wash and collecting shells. This is not something I ever wish to grow out of.

About half way along, with Sheringham seemingly no closer, there are some grassy hills
which provide a nice variety. Eventually, near Weybourne, cliffs begin to appear in
front and the path takes you up there. The views are lovely and the terrain takes on an
undulating nature that we hadn't seen until this point. Eventually we would pass a golf
course and reach the lifeboat station on the edge of Sheringham. It's then a walk along
the promenade into one of the prettiest seaside towns in Norfolk.

*** Day 5: Sheringham to Bacton
# 17th September 2022

#+hugo: {{<mini-map-bounds bounds="1.2131382431834936,52.94532135128975,1.4771898183971643,52.85138829611242">}}

#+begin_pictures
ncp/day5/IMG_2454
ncp/day5/IMG_2528
ncp/day5/IMG_2551
ncp/day5/IMG_2582
ncp/day5/IMG_2599
ncp/day5/IMG_2651
ncp/day5/IMG_2718
#+end_pictures

We returned to Sheringham by train from Norwich. An incoming wind gave the sea, and
somehow the whole town, a completely different character that morning, perhaps preparing
us for the wilder part of the walk yet to come.

Continuing along the promenade to the east we soon reached the edge of Sheringham and
the Beeston Bump which, at 63 m, is a notable hill for Norfolk (the actual highest point
in Norfolk, Beacon Hill, stands at 105 m only a kilometre or so inland from here).

The NCP here begins to take on the character that dominates the second half. Long gone
are the salt marshes; here we see endless sandy beaches, cliffs and constant reminders
of a sad fact: this part of the country is literally disappearing into the sea. Norfolk
is one of the most rapidly eroding areas in the country.

We walked most of the way along the cliff towards Cromer but in many places the path has
been diverted inland due to erosion. One part in particular was so close to the edge it
will surely be gone in a few years.

After a brief tour of Cromer including the famous pier and Grey Seal Coffee we said
goodbye to the last large town and public transport connection before the end. Out of
Cromer the NCP actually takes you underneath the cliff on to the beach, but we
mistakenly walked on top of the cliff. But there were no regrets because this part of
the walk was stunning, reminding me more of the South Coast.

After some easy going cliff top walking we descended on to the beach at Mundesley for
the last stretch to Bacton. Due to the gas terminal at Bacton this is one part of the
Norfolk coastline that has been protected by extending the beach outwards. Our day ended
on the beach here with a sunset creating beautiful colours.

*** Day 6: Bacton to Hemsby
# 18th September 2022

#+hugo: {{<mini-map-bounds bounds="1.4773163013160229,52.85447761416435,1.7039009369909763,52.689558221027255">}}

#+begin_pictures
ncp/day6/IMG_2833
ncp/day6/IMG_2839
ncp/day6/IMG_2868
ncp/day6/IMG_2922
ncp/day6/IMG_2939
ncp/day6/IMG_2948
ncp/day6/IMG_3082
#+end_pictures

Back to Bacton the next day and our walk started with some light rain. Our jackets and
bag covers would be on most of the day, but one rainy day out of seven is not bad going!

This was the most remote day of them all with just a few small settlements along the
way. It was also the longest at 25 km. We got into our stride and could soon see the
classic red and white lighthouse at Happisburgh (pronounced ˈheɪzbʌrə, like
"hays-burra"). This is one of the most eroded towns with entire rows of houses already
lost to the sea.

Just after Happisburgh we stopped at Smallsticks Café for some coffee and cake in a
charming beach chalet. We then pushed on to Sea Palling for our lunch at the chip shop.

The rain set in again after lunch as we walked along more beaches, dunes and sea walls
towards one of Norfolk's local wonders: the seals at Horsey Gap. A large colony of grey
seals has taken up residence on the beaches between Horsey and Winterton. At this time
of year the pups are around 9 months old and the seals just like to lounge on the
beach. There were so many at one part that we were forced off the beach and into the
dunes.

Winterton Dunes sat between Horsey and our bed for the night in Hemsby. The dunes were
quite unique and seemed endless no doubt thanks to our aching feet and rapidly fading
light. It was a Sunday the day before the Queen's funeral and we had placed all of our
hope for dinner on a single Co-op located in Hemsby. Luckily it was still open and our
dinner consisted entirely of reduced items. Our bed was in the depths of the caravan
park which seemed like a maze in what was now complete darkness. Luckily we did bring
our head torches.

*** Day 7: Hemsby to Hopton
# 19th September 2022

#+hugo: {{<mini-map-bounds bounds="1.701243706047535,52.69137960858643,1.7396469041705132,52.53630400635302">}}

#+begin_pictures
ncp/day7/IMG_3200
ncp/day7/IMG_3213
ncp/day7/IMG_3262
ncp/day7/IMG_3343
ncp/day7/IMG_3409
ncp/day7/IMG_3440
ncp/day7/IMG_3461
#+end_pictures

The final day of the walk was a bit different. The beaches here are probably the most
gorgeous in the whole county (perhaps even the country). That means from here all the
way to the end at Hopton is a prime holiday-making spot. It's not remote and, in fact,
we'd be walking right through one of Norfolk's larger urban centres.

But today was really different because it was the Queen's funeral. It was long past
prime holiday season, but even at Caister it felt eerily quiet. We walked past the
caravan parks and the dunes on the edge of Great Yarmouth and on through the Venetian
Waterways. Yarmouth was dead, as if it was Christmas day, except the weather was
glorious.

It was necessary to cross the River Yare in to Gorleston and continue the walk along the
docks. There are some sights to be seen, but this part of the walk did grind on a
bit. Dockyards are very large and boring places to traverse on foot.

Eventually we exited the dockyards and reached the beach at Gorleston. What a wonderful
sight! It's such a juxtaposition with the beautiful golden sand on one side the moody,
rusty docks on the other.

For the final part of the walk I neglected to check the tide times. We were forced to
walk behind the sea defences on a narrow piece of beach. It was a tiny bit scary at
times as the sea was crashing heavily against the wooden groynes and threatening to cut
us off in places. There is an alternative route, but we needed to catch a bus at the end
and found ourselves committed to the beach.

Eventually near Hopton there was a way off the beach and the tide forced us to take
it. We scurried through another maze of a caravan park to get to the official end, took
a couple of pictures with the sign, looked briefly onwards towards Suffolk, then darted
back to the bus stop.

** Reflection

#+hugo: {{<mini-map-section>}}

#+hugo: {{<mini-map-bounds bounds="0.396881,52.495323,1.812744,53.023870">}}

Norfolk has always been special to me. When I was little we used to have our summer
holidays in Caister and Hopton. It seemed a million miles away back then. Later I would
move to Norwich for my studies and lived there for 10 years. Even after moving to
Norwich it still took a few years for my world to shrink and for me to realise I could
go to some of these places again. On my bike and later by car I ended up visiting many
of the places along the coast.

But I hadn't seen all of it. I was aware of the Norfolk Coast Path and have a picture I
took of the sign back in 2017 when the path ended at Cromer. It just never occurred to
me that I could actually do it. Thanks to Vicki I now know how to do long-distance walks
and I can now say I've seen the entire Norfolk Coast.

The NCP seems like a great introduction to long-distance walking too. Especially the
first half. But I doubt anyone would get to Cromer and want to stop. But then again, you
never do. There is a Suffolk Coast Path and we definitely intend to do it as a kind of
sequel to the NCP.

There's nothing like walking as a way to experience the planet. Even cycling isn't the
same. You can literally feel it against your feet: every undulation, every
texture. Unlike other modes of transport walking happens mostly subconsciously. Your
mind is free to see everything, hear everything and smell everything. Plus you can stop
at any moment if something is worth some extra time.

This was my first long-distance walk and I had a wonderful time. It's a great
introduction to long-distance walking and one that I'd highly recommend!

* TODO Camino Gran Canaria                             :walking:spain:camino:
:PROPERTIES:
:EXPORT_FILE_NAME: camino-gran-canaria
:END:

* TODO Camino Primitivo                                :walking:spain:camino:
:PROPERTIES:
:EXPORT_FILE_NAME: camino-primitivo
:END:
