#!/usr/bin/env bash

# TODO use make pattern rules to do this?

find src-images/ -type d -printf 'static/web-images/%P\n' | xargs mkdir -p

for f in $(find src-images/ -type f -iregex '.*jpe?g$'); do
    echo "converting $f"
    d=$(dirname ${f#src-images/})
    fname=$(basename ${f%.*})
    convert $f -auto-orient -resize 500x500 -strip -quality 78 static/web-images/$d/$fname-sm.jpeg
    convert $f -auto-orient -resize 1920x1080 -strip -quality 86 static/web-images/$d/$fname.jpeg
done
