#+TITLE: Calendars
#+DATE: 2022-01-13T14:05:22Z
#+DRAFT: true
#+DESCRIPTION:
#+CATEGORIES[]:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Why are we still using paper-like calendars?

Bit about Gutenberg press.

HN comments:

Thunderbird has the only calendar I know that has a "multiweek" display as opposed to
(well, in addition to) the utterly retarded month view that exists in every other GUI.

We've been doing electronic calendars for how long now? Why are we still using a
paradigm from paper based calendars? At the beginning of a month I can see three weeks
ahead, but at the end of the month I can see three weeks behind. It frustrates me no end
that this is still a thing. It reminds me of the early days of Google maps when they
were no better than paper maps, but now we can rotate the map, zoom in and out etc. But
calendars are still no better than paper calendars. Apart from the one in Thunderbird.

---

It did have zoom, but they were fixed levels so no different to having multiple paper
maps at different scales. Yes, of course there is the advantage that it's "not paper",
but that was the only advantage really. This is not unexpected at all as new technology
very often mimics existing technology in its first iteration. If you look at the first
outputs of the Gutenberg press you can see they were trying to mimic handwritten books
of the time. But usually the new technology very quickly surpasses the old after the
first iteration, as electronic maps have now done.
