#+TITLE: Do You Really Think Imperatively?
#+DATE: 2021-11-16T21:40:45Z
#+DRAFT: true
#+DESCRIPTION:
#+CATEGORIES[]: programming
#+TAGS[]: programming functional-programming
#+KEYWORDS[]: functional programming
#+SLUG:
#+SUMMARY:

I've read several articles claiming that functional programming is difficult or
unpopular because it doesn't match the way we think. In particular, some claim that a
functional style forces one to think "backwards" while imperative programming allows us
to think "forwards".

A popular analogy for this is writing a recipe for a cake. It's true, if you look up a
recipe for a cake you will probably find it written in an imperative style. That is to
say it tells you /how/ to make the cake; it proceeds "forwards" in the same direction
one would proceed when executing the recipe. But does this actually match the way we
/think/? Is it even the best way to write a recipe?

The first thing to note is that an experienced cook does not approach a recipe in
complete isolation. What might be a new dish to the cook almost certainly draws on many
skills, techniques and even "sub-recipes" already known. The mother sauces comprise a
small handful of sauces integral to French cuisine. Cooks versed in the cuisine do not
need to read a recipe for a mother sauce each time it is used. They know how to whisk
and how to keep eggs from curdling. A succinct recipe for macaroni cheese for someone
versed in French cuisine could be simply "macaroni pasta in a cheese sauce".

Is this backwards thinking? After all, I've only told the cook what macaroni cheese /is/
and not /how/ to make it. But I am certain a cook who has never heard of macaroni
cheese, but knows how to make cheese sauce and knows what pasta is, would be able to
execute this recipe. Seems like forward thinking to me.

I would argue that recipes written in an imperative style are actually quite frustrating
to an experienced cook. If I were to read a whole recipe only to find out I've read yet
another description of béchamel sauce I'd feel like I'd wasted my time. This is why good
cookbooks don't do this; they'll refer you to other recipes for the common
elements. Online recipes tend to be all-inclusive and I often find them frustrating.

Despite me calling them "sub-recipes" earlier, I think these common elements of cooking
are more like functions than subroutines. It comes completely naturally to a cook to
prepare two or more foods simultaneously and in complete isolation---in separate threads
of execution, if you will. This concept is intuitive to anyone. If I say you need a
sauce and some cooked pasta I would not expect you to attempt to produce both in the
same pot at the same time. We just don't think like that.

To take the analogy to its limits, let's consider the existence of higher-order
functions in the kitchen. Not even the most verbose recipe out there tells you to shape
your biscuits one by one. It's simply implied that to build an array of biscuits you
produce one biscuit for every space on the tray. This is map. And mixing all those
ingredients together at the end? That's reduce (with the binary operator "mix").

But I think the most convincing argument against imperative thinking is simply that we
are not automata. We do not perform mindless tasks in isolation. If a fellow human
enters your kitchen and enquires on your activity you wouldn't tell him you are mixing
flour into water. You'd tell him you're making a cake. You always know what the end
result is. Otherwise you'd never get there. Recipes aren't written imperatively because
this is how we think. They are written this way because it's a reasonably effective way
of recording them in written English. This does not by any means imply it matches the
way we think or that it's the only way to effectively communicate a recipe.

Imperative programming is a learned skill. This is not something that comes intuitively
to most people. If you tried to teach people in the same way you "teach" a computer to
sort numbers I doubt you would find much success. But try telling someone you need a
shuffled deck of cards and they'll either shuffle it or they'll ask how. If this is
thinking backwards then consider me backwards.
